spring.application.name=labA-1

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/labs
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

